name = "Imperial Accord"
author = "Oftiks"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba65e5dfdbbe5969cea14396dd698804b74c52aaa0a256474bca0567a0c2964f"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
