name = "Imperial Accord"
author = "Oftiks"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebd866a0c19fd1b2f677e00eff823a1d436c63907620ab50d1e8513193435ec1"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
